# Generated by Django 5.0.4 on 2024-08-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_contactemail_project_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contact_email',
            new_name='contactEmail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
