# Generated by Django 5.0.4 on 2024-08-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_applicationresponse_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='additional_questions',
            field=models.TextField(blank=True, help_text='Additional questions added by the professor', null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='questions',
            field=models.TextField(default='When did you join the University?; What course are you in?; Why are you interested in this project?'),
        ),
    ]
