# Generated by Django 5.0.4 on 2024-08-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_applicationform_additional_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='questions',
            field=models.TextField(default='When did you join the University?, What course are you in?, Why are you interested in this project?'),
        ),
    ]
